#!/usr/bin/env python
# -*- coding: utf-8 -*-

__mtime__ = '2019/11/6'


PPT_WORD_FILTER=['极简办公','极简网','极简','小简','优品PPT','优品','ypppt','策划人','INFOGRAPHIC','小店','58pic.com',
             'Best Presentation','Youka','.com','研究院','思翔PPT','ASADAL','Asadal','asadal','ytfcells','jjppt',
             '.cn','DESIGN','design','Design','name','Name','锐普','Designed','乐配','D意空间','好儿女','姚米多',
             'NAME','该原创PPT来自','Designed by','Spring and Autumn','小政','购买','梭拓','思源','zero','斯坦森',
                '为您提供全方位的演示服务','我们拥有优秀的专业设计团队','专注于专业精致的PPT设计与制作','spring and autumn',
             'OfficePLUS','OFFICE PLUS','PRESENTED BY','JOHN DOE','John Doe','创始人','制作','尘电','青鸟演示','十年之约',
                '我是小蜜作品','Peter','SIMON PPT','@','公众号','读书笔记','演届网','美仑设计','风云网','黄色方块','Yexue',
             'LEOPARD','leopard','Leopard','LEOPRAD','野百合','售后','定制','文案','向天歌','搜索','DD设计','大音希声',
            '极简主义','PPT设计','骆可可','洛可可','极简导师','简一设计','艺随风','链接','店铺','春秋视觉','帅英雄','NEWBP',
            '稻壳导师','酱紫鱼','更多','工作室','少先队员','喵星人服务设计','KJ设计','皮皮虾','深度想象','碧城恭','意空间',
             '模板网','小鱼','五视觉','房飞扬','刘杰红','非鱼','DD','张三','李氏春秋','李老师','Shadow','沐心','夏影','出品',
                '一生清浅','猫特','一只叫雪莉的猫咪','奇怪达人','林平平','张林依','千图网','千图','58PIC.COM','酒馆无酒','佳誉设计',
                 'Joyce','挥小霍','NewBeeRen','BRUCE','bruce','叶雪','dgeegegd','JERRY','黄小葵','斯柯达','COOLLA','梦工厂','xiao',
                 '春秋广告','海宝','MOUMOUMOU','韩梅梅','张无忌','秋实','火星原驻民','牛大人','字在演示','小成','普屏','哎呀52',
                 '一张国字脸','洛羊','安妮','李雷','D意','墨 客','墨客','KGDXMG','Asoledad','Shirley','就 爱 清 新 文 艺 范',
                 '就 爱 清 新 文 艺 范','不一样的烟火','林姝雨','呆萌怪大叔','牛魔王的结发妻子','Lisa','Damon','斯 坦 森','熊猫老师',
                 '熊猫达人','汤圆君','然而会做PPT','喵星人','小小','七月无伤','yebaihe','LUSIR','sloganslogan','Haifeng','E风设计',
                 'E风','百度','topppt','知美','烁儿','稻壳','维佳','三更精品','Nickel Lee','荆晓谁','王晓谁','唐伯虎','余秋香','吴先生',
                 '蓝梦','Alan','九芒设计','小 城','FLYING IMPRESSION','小清新演示','Mr zhang','Nador','叶   雪','大中国','我是小蜜',
                 '李心','MrWu','同道堂','李望珍','Xdongye','千小图','http://www.58pic.com','58pic','悦枫明','John Whittak','千图老师',
                '极致无岸','向天而歌','KJ','kongjing','小夏','Jason','Zhuyushanren','Mr·Monster','怪兽先生','Monster','姜公子','HAISON',
                 '小城','稻老师','Tony Gao','呵呵玉','WANMEIYANYI','Dai Meng Guai Da Shu ','博文','Will','星染','熊猫','丘皮特','千千',
                 '燕雅飞的窝','蓝点形象设计','www.qiantu.com','NADOR','SPACE STUDIO','千小兔','一点设计','郝帅','JIN VISUAL','JinShiJie',
                 'MOUMOU','飒飒','水感觉','宣蓉','四比三','偷花','小果果','最美桃花','妙点萌','sunny啊飘','幽夏','幽夏PPT','柴大大','四角猫',
                 'sweet演示','哎呀','MISSIE ROSEYEI','几岁了','王晓凌厉','JIAYU','微鱼','dabao','WPS','金山','幻享','CHUNQIU','HUMEILI',
                'QIANTU','www.qiantu.com','XIAOZHEN','妈妈咪','前行者','盗卖','原创','千圖网','千圖','588ku.com','千库网','千库','SUN_PPT',
                 'SUNPPT','sun','SLOGAN','王小凌厉','809研究处','CHEN','非凡图库','HYDROGEN','HYDROGEN PPT','墨尘','Maggic','千小库',
                 'KINGPUB','licai2011','我图网','Flying Impression','ZHAOFEI','Zhao','Fei','洋大师','风云办公','成达素材','佳誉','LUOYANG',
                 'JAIYU','kuku','库库','意涵设计','海洛设计','旦角儿','zoey','优美PPT','小百合','雪儿','菜菜PPT','小螃蟹','Qian Ku Wang',
                 'JIUJIU','Tony Yang','Dong-ye','春秋数据','春秋','夏微凉','小奕','叶落飘雪','小笼包','ibaotu','包图','包小图','BAO TU WANG',
                 'baotu','小图图','包图网','李世民','赵春波','城北慕南','Zero','ZERO','完美演绎','素材下载','网络平台','角落漫想','哈赛','氢设计',
                 '小包总','DONGYE','Dong Ye','菜菜','韩创电子科技','技术论坛','素材商城','下载','包小白','IBAOTU','小包子','Baotuwang','Simple Lee',
                '果果','Tony Zhang','588ku','taobao','借车偷花','飞印象','fly impression','Flying impression','IBAO.COM','小河北作品',
                 '请勿商用','晋视界','贾克斯','东成西就','qian ku wang','喵星','李益达','逼格','tretars','逗比','daoke','町裦设计','糖花儿','壹视界',
                 '香草','Baotu','花儿设计师','zj','大冬瓜','588KU','千 库 网','原味','DAYIN','大叔','BAOTU','Ones DE','壹德设计','小象演示','赵美丽',
                 'ABC童鞋','ABC','QIAN KU WANG','小幺','王二','半想象现实','变色龙','zhaomeili','乐配视觉','走心PPT','走心','奕宁ppt','奕宁','小马创意',
                 'zaobigongshe','赵一博','在想PPT','Qian ku','Da yan','小包包','静水流深','DONG-YE','JMPPT','选购','脑洞创意','芒果包','Jayden','shuttle',
                 '曼陀罗','南忱','小咕咚','商务交互演示视觉','格迪天','DISIGNED','docer','智慧办公','珊瑚设计','珊瑚','懒散','喵五郎','挥霍','复亮亮','旗舰店',
                'FEI ER SHE JI','二营长','Huihuo','huihuo','二哈','BOBY','BT','DKE','BAO TU','2850856404','dai2000','小河北','稀饭','办公作品','PANDA',
                 '五角猫','设计中国','包先生','包美女','包女士','心创未来','Janice','作品被黑','大兔兔','张小张','Zhang Xiao Zhang','木子','YUEYUE','PANDAREN',
                 '啊飘','Copyright','©','ANGELA','璞原','大大包','南方演示','古风设计','Jack_chen','阿炼','包包','包子','DAO KE','DAO','KE','梦想稀飯',
                 '发条君','tacyppt','呵 呵 玉','小包','一栀小仙女','蒲蒲','蜜丝','泡泡糖','赤木','小象','Shuttle','李 小 猫','李小猫','北极演示','Olivia',
                 '唐七彩','夏末未至','Bao','BAO','Tu','tu','XIAYING','多肉','ALONIC','IRIS','小巴学车','丑八怪伊阿伊啊哎','琪图欧','庄老师','KDBR','yexue',
                 '喵 星 人 服 务 设 计','58pc','shizhanpai','可爱包','Xia Weilaing','fid888','消炎酱','李小双','BaoTu','276060523','18928897164','whishile',
                 '冰冰棒','七芒星','DALI','李诗岚','洛羊PPT','洛羊','做设计','不抠图','宋登辉','图图','RIGHTS','rights','Rights','境海天腾','在想','13512345678',
                 'ljh','半想象','DOCER','虹猫设计','有个小人','小图','QIANKU','HaiFeng','JM','三人行','千·库·网','Xiao Zheng','jiaoyang','Slidefabric','锐意进取',
                 '普及精品','588','摇滚基因','维权','侵权','RAPI','摄图网','摄图','699pic','699PIC','699Pic','699','tukuppt','熊猫办公','熊猫','xiongmao','Xiongmao','XIONGMAO',
                 'XiongMao','小熊猫','大熊猫','空间','Panda','panda','库','摄影图','正版','图库','办公','包 图 网','版权','安生泡','site2max','谷木','风之谷','摄影',
                 'BOSSPPT','ART.TRIP','TUKUPPT','优木视觉','映山居','稻 壳','稻','壳','BAOTUWANG','MOSHAN','千','Slidefabric','素材','网站','58ku','零度演示','香草PPT',
                 '包老师','ooopic','密斯特道','DESTINY','FREEDOM','菲迩设计','hepanji','bao',
             ]
